import { 
  Type, 
  Scissors, 
  Binary, 
  LayoutGrid,
  Minimize2,
  FileDown,
  Code,
  Wand2,
  Chrome,
  FileCode
} from 'lucide-react';

export const TOOLS = [
  {
    id: 'url-trimmer',
    name: 'URL Trimmer',
    description: 'Clean URL lists by stripping parameters.',
    icon: Scissors,
    category: 'SEO',
    href: '/',
    status: 'Active',
    isPopular: true,
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Analyze text structure and counts.',
    icon: Type,
    category: 'Writing',
    href: '/tools/word-counter',
    status: 'Ready',
    isPopular: true,
  },
  {
    id: 'text-to-image',
    name: 'AI Text-to-Image',
    description: 'Create high-quality stunning graphics from prompts.',
    icon: Wand2,
    category: 'Graphics',
    href: '/tools/text-to-image',
    status: 'Ready',
    isPopular: true,
  },
  {
    id: 'pdf-converter',
    name: 'PDF Converter',
    description: 'Images to PDF high-quality conversion.',
    icon: FileDown,
    category: 'PDFs',
    href: '/tools/pdf-converter',
    status: 'Ready',
    isPopular: true,
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Reduce size while keeping quality.',
    icon: Minimize2,
    category: 'Graphics',
    href: '/tools/image-compressor',
    status: 'Ready',
    isPopular: true,
  },
  {
    id: 'image-converter',
    name: 'Image Converter',
    description: 'Convert between imaging formats.',
    icon: LayoutGrid,
    category: 'Graphics',
    href: '/tools/image-converter',
    status: 'Ready',
    isPopular: true,
  },
  {
    id: 'text-to-html',
    name: 'Text to HTML',
    description: 'Convert plain text to clean HTML code instantly.',
    icon: Code,
    category: 'Writing',
    href: '/#workspace',
    status: 'Ready',
    isPopular: true,
  },
  {
    id: 'chrome-extension',
    name: 'Chrome Extension',
    description: 'Load Word Counter as a browser extension.',
    icon: Chrome,
    category: 'Extensions',
    href: '/tools/chrome-extension',
    status: 'Ready',
  },
  {
    id: 'sitemap-generator',
    name: 'Sitemap Generator',
    description: 'Crawl website pages and generate valid XML sitemaps.',
    icon: FileCode,
    category: 'SEO',
    href: '/tools/sitemap-generator',
    status: 'Ready',
    isPopular: true,
  }
];

export const CATEGORIES = ['All', 'Writing', 'SEO', 'Graphics', 'PDFs', 'Extensions'];
